- name: content
  color: "ffa69e"
  description: Issues related to creating, updating, or managing content
- name: dependencies
  color: "26547c"
  description: Pull requests to update dependency files, ensuring packages and libraries are up-to-date
- name: dev
  color: "faf3dd"
  description: Issues involving development tasks, bug fixes, features, and code refactoring
- name: javascript
  color: "ffd166"
  description: Pull requests updating JavaScript code, affecting front-end functionalities and scripts
- name: php
  color: "06d6a0"
  description: Pull requests updating PHP code, impacting back-end functionalities and server-side scripts
- name: released
  color: "ef476f"
  description: Issues that have been addressed and released by semantic release
- name: ui
  color: "b8f2e6"
  description: Issues on UI design or modification, focusing on visual aspects and user interaction
- name: ux
  color: "aed9e0"
  description: Issues enhancing user experience, addressing usability, accessibility, and satisfaction
