name: Sync Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  sync_labels:
    name: Sync Labels
    runs-on: ubuntu-latest

    steps:
      - name: Run Label Syncer
        uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/21stdigital/workflows/main/.github/labels.yml
          delete-other-labels: false
          token: ${{ secrets.GITHUB_TOKEN }}
