name: Sync Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  sync_labels:
    name: Sync Labels
    runs-on: ubuntu-latest

    steps:
      - name: Download Latest Label Definitions
        run: |
          curl -s --retry 5 \
            "https://raw.githubusercontent.com/21stdigital/workflows/main/.github/labels.yml" \
            -o labels.yml

      - name: Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: labels.yml
